import type { TableRecord } from "./types";

function generateCompanyRecords(): TableRecord[] {
  const companies: Array<Record<string, unknown>> = [
    {
      fld_company_name: "Acme Inc",
      fld_company_type: "B2B SaaS",
      fld_company_revenue: 1200000,
      fld_company_status: "Active",
      fld_company_email: "contact@acme.com",
      fld_company_website: "https://acme.com",
      fld_company_phone: "5551234567",
      fld_company_founded: "2018-03-15",
      fld_company_active: true,
      fld_company_tags: ["Enterprise", "Mid-market"],
    },
    {
      fld_company_name: "TechCorp Solutions",
      fld_company_type: "E-commerce",
      fld_company_revenue: 850000,
      fld_company_status: "Lead",
      fld_company_email: "info@techcorp.io",
      fld_company_website: "https://techcorp.io",
      fld_company_phone: "5559876543",
      fld_company_founded: "2019-06-22",
      fld_company_active: false,
      fld_company_tags: ["Startup"],
    },
    {
      fld_company_name: "StartupXYZ",
      fld_company_type: "Fintech",
      fld_company_revenue: 2500000,
      fld_company_status: "Active",
      fld_company_email: "hello@startupxyz.com",
      fld_company_website: "https://startupxyz.com",
      fld_company_phone: "5552345678",
      fld_company_founded: "2021-01-10",
      fld_company_active: true,
      fld_company_tags: ["Enterprise", "Startup"],
    },
    {
      fld_company_name: "MedVita Health",
      fld_company_type: "Healthcare",
      fld_company_revenue: 4200000,
      fld_company_status: "Active",
      fld_company_email: "partnerships@medvita.com",
      fld_company_website: "https://medvita.com",
      fld_company_phone: "5553456789",
      fld_company_founded: "2016-09-01",
      fld_company_active: true,
      fld_company_tags: ["Enterprise"],
    },
    {
      fld_company_name: "LearnPath",
      fld_company_type: "EdTech",
      fld_company_revenue: 620000,
      fld_company_status: "Active",
      fld_company_email: "sales@learnpath.io",
      fld_company_website: "https://learnpath.io",
      fld_company_phone: "5554567890",
      fld_company_founded: "2020-04-18",
      fld_company_active: true,
      fld_company_tags: ["Startup", "SMB"],
    },
    {
      fld_company_name: "CloudNine Systems",
      fld_company_type: "B2B SaaS",
      fld_company_revenue: 3100000,
      fld_company_status: "Active",
      fld_company_email: "enterprise@cloudnine.dev",
      fld_company_website: "https://cloudnine.dev",
      fld_company_phone: "5555678901",
      fld_company_founded: "2017-11-05",
      fld_company_active: true,
      fld_company_tags: ["Enterprise", "Mid-market"],
    },
    {
      fld_company_name: "ShopFlow",
      fld_company_type: "E-commerce",
      fld_company_revenue: 1800000,
      fld_company_status: "Active",
      fld_company_email: "hello@shopflow.co",
      fld_company_website: "https://shopflow.co",
      fld_company_phone: "5556789012",
      fld_company_founded: "2019-02-28",
      fld_company_active: true,
      fld_company_tags: ["Mid-market"],
    },
    {
      fld_company_name: "PayGuard",
      fld_company_type: "Fintech",
      fld_company_revenue: 5600000,
      fld_company_status: "Active",
      fld_company_email: "biz@payguard.com",
      fld_company_website: "https://payguard.com",
      fld_company_phone: "5557890123",
      fld_company_founded: "2015-07-12",
      fld_company_active: true,
      fld_company_tags: ["Enterprise"],
    },
    {
      fld_company_name: "WellnessHub",
      fld_company_type: "Healthcare",
      fld_company_revenue: 320000,
      fld_company_status: "Lead",
      fld_company_email: "info@wellnesshub.org",
      fld_company_website: "https://wellnesshub.org",
      fld_company_phone: "5558901234",
      fld_company_founded: "2022-08-20",
      fld_company_active: false,
      fld_company_tags: ["SMB"],
    },
    {
      fld_company_name: "DataPulse Analytics",
      fld_company_type: "B2B SaaS",
      fld_company_revenue: 980000,
      fld_company_status: "Active",
      fld_company_email: "contact@datapulse.ai",
      fld_company_website: "https://datapulse.ai",
      fld_company_phone: "5559012345",
      fld_company_founded: "2020-12-01",
      fld_company_active: true,
      fld_company_tags: ["Startup", "Mid-market"],
    },
    {
      fld_company_name: "GreenLeaf Energy",
      fld_company_type: "B2B SaaS",
      fld_company_revenue: 7200000,
      fld_company_status: "Active",
      fld_company_email: "partners@greenleaf.energy",
      fld_company_website: "https://greenleaf.energy",
      fld_company_phone: "5550123456",
      fld_company_founded: "2014-05-30",
      fld_company_active: true,
      fld_company_tags: ["Enterprise"],
    },
    {
      fld_company_name: "QuickShip Logistics",
      fld_company_type: "E-commerce",
      fld_company_revenue: 1500000,
      fld_company_status: "Churned",
      fld_company_email: "ops@quickship.com",
      fld_company_website: "https://quickship.com",
      fld_company_phone: "5551112222",
      fld_company_founded: "2018-10-15",
      fld_company_active: false,
      fld_company_tags: ["Mid-market"],
    },
    {
      fld_company_name: "NovaByte",
      fld_company_type: "B2B SaaS",
      fld_company_revenue: 450000,
      fld_company_status: "Lead",
      fld_company_email: "hello@novabyte.io",
      fld_company_website: "https://novabyte.io",
      fld_company_phone: "5552223333",
      fld_company_founded: "2023-01-12",
      fld_company_active: true,
      fld_company_tags: ["Startup", "SMB"],
    },
    {
      fld_company_name: "SecureVault",
      fld_company_type: "Fintech",
      fld_company_revenue: 3800000,
      fld_company_status: "Active",
      fld_company_email: "sales@securevault.com",
      fld_company_website: "https://securevault.com",
      fld_company_phone: "5553334444",
      fld_company_founded: "2016-03-22",
      fld_company_active: true,
      fld_company_tags: ["Enterprise", "Mid-market"],
    },
    {
      fld_company_name: "BrightMinds Academy",
      fld_company_type: "EdTech",
      fld_company_revenue: 890000,
      fld_company_status: "Active",
      fld_company_email: "team@brightminds.edu",
      fld_company_website: "https://brightminds.edu",
      fld_company_phone: "5554445555",
      fld_company_founded: "2019-08-05",
      fld_company_active: true,
      fld_company_tags: ["Mid-market"],
    },
    {
      fld_company_name: "PixelForge",
      fld_company_type: "B2B SaaS",
      fld_company_revenue: 1100000,
      fld_company_status: "Active",
      fld_company_email: "info@pixelforge.design",
      fld_company_website: "https://pixelforge.design",
      fld_company_phone: "5555556666",
      fld_company_founded: "2021-06-14",
      fld_company_active: true,
      fld_company_tags: ["Startup"],
    },
    {
      fld_company_name: "HealthSync",
      fld_company_type: "Healthcare",
      fld_company_revenue: 2200000,
      fld_company_status: "Active",
      fld_company_email: "connect@healthsync.io",
      fld_company_website: "https://healthsync.io",
      fld_company_phone: "5556667777",
      fld_company_founded: "2017-12-09",
      fld_company_active: true,
      fld_company_tags: ["Enterprise"],
    },
    {
      fld_company_name: "SwiftPay",
      fld_company_type: "Fintech",
      fld_company_revenue: 670000,
      fld_company_status: "Lead",
      fld_company_email: "bizdev@swiftpay.co",
      fld_company_website: "https://swiftpay.co",
      fld_company_phone: "5557778888",
      fld_company_founded: "2022-03-01",
      fld_company_active: true,
      fld_company_tags: ["Startup", "SMB"],
    },
    {
      fld_company_name: "RetailEdge",
      fld_company_type: "E-commerce",
      fld_company_revenue: 4100000,
      fld_company_status: "Active",
      fld_company_email: "partnerships@retailedge.com",
      fld_company_website: "https://retailedge.com",
      fld_company_phone: "5558889999",
      fld_company_founded: "2015-11-20",
      fld_company_active: true,
      fld_company_tags: ["Enterprise", "Mid-market"],
    },
    {
      fld_company_name: "CodeStream Labs",
      fld_company_type: "B2B SaaS",
      fld_company_revenue: 290000,
      fld_company_status: "Churned",
      fld_company_email: "team@codestream.dev",
      fld_company_website: "https://codestream.dev",
      fld_company_phone: "5550001111",
      fld_company_founded: "2021-09-30",
      fld_company_active: false,
      fld_company_tags: ["SMB"],
    },
    {
      fld_company_name: "EduWave",
      fld_company_type: "EdTech",
      fld_company_revenue: 1350000,
      fld_company_status: "Active",
      fld_company_email: "admin@eduwave.com",
      fld_company_website: "https://eduwave.com",
      fld_company_phone: "5551239876",
      fld_company_founded: "2018-07-04",
      fld_company_active: true,
      fld_company_tags: ["Mid-market", "SMB"],
    },
    {
      fld_company_name: "AeroVista",
      fld_company_type: "B2B SaaS",
      fld_company_revenue: 8900000,
      fld_company_status: "Active",
      fld_company_email: "enterprise@aerovista.com",
      fld_company_website: "https://aerovista.com",
      fld_company_phone: "5559871234",
      fld_company_founded: "2013-02-14",
      fld_company_active: true,
      fld_company_tags: ["Enterprise"],
    },
  ];

  return companies.map((data, index) => ({
    id: `rec_company_${index + 1}`,
    objectId: "obj_companies",
    data,
    createdAt: new Date(2025, 0, index + 1).toISOString(),
    updatedAt: new Date(2026, 2, 15 + (index % 14)).toISOString(),
  }));
}

function generateContactRecords(): TableRecord[] {
  const contacts: Array<Record<string, unknown>> = [
    {
      fld_contact_name: "Sarah Johnson",
      fld_contact_email: "sarah.johnson@acme.com",
      fld_contact_phone: "5551234001",
      fld_contact_company: "Acme Inc",
      fld_contact_role: "VP of Sales",
      fld_contact_linkedin: "https://linkedin.com/in/sarahjohnson",
      fld_contact_tags: ["Decision Maker"],
      fld_contact_last_contacted: "2026-03-20",
    },
    {
      fld_contact_name: "Mike Chen",
      fld_contact_email: "mike.chen@techcorp.io",
      fld_contact_phone: "5551234002",
      fld_contact_company: "TechCorp Solutions",
      fld_contact_role: "CTO",
      fld_contact_linkedin: "https://linkedin.com/in/mikechen",
      fld_contact_tags: ["Decision Maker", "Champion"],
      fld_contact_last_contacted: "2026-03-18",
    },
    {
      fld_contact_name: "Emily Davis",
      fld_contact_email: "emily@startupxyz.com",
      fld_contact_phone: "5551234003",
      fld_contact_company: "StartupXYZ",
      fld_contact_role: "Head of Product",
      fld_contact_linkedin: "https://linkedin.com/in/emilydavis",
      fld_contact_tags: ["Champion", "Influencer"],
      fld_contact_last_contacted: "2026-03-15",
    },
    {
      fld_contact_name: "James Wilson",
      fld_contact_email: "james.wilson@medvita.com",
      fld_contact_phone: "5551234004",
      fld_contact_company: "MedVita Health",
      fld_contact_role: "CEO",
      fld_contact_linkedin: "https://linkedin.com/in/jameswilson",
      fld_contact_tags: ["Decision Maker"],
      fld_contact_last_contacted: "2026-03-22",
    },
    {
      fld_contact_name: "Lisa Park",
      fld_contact_email: "lisa.park@learnpath.io",
      fld_contact_phone: "5551234005",
      fld_contact_company: "LearnPath",
      fld_contact_role: "Director of Engineering",
      fld_contact_linkedin: "https://linkedin.com/in/lisapark",
      fld_contact_tags: ["Influencer", "End User"],
      fld_contact_last_contacted: "2026-03-10",
    },
    {
      fld_contact_name: "Alex Rodriguez",
      fld_contact_email: "alex@cloudnine.dev",
      fld_contact_phone: "5551234006",
      fld_contact_company: "CloudNine Systems",
      fld_contact_role: "VP of Engineering",
      fld_contact_linkedin: "https://linkedin.com/in/alexrodriguez",
      fld_contact_tags: ["Decision Maker", "Champion"],
      fld_contact_last_contacted: "2026-03-25",
    },
    {
      fld_contact_name: "Rachel Kim",
      fld_contact_email: "rachel.kim@shopflow.co",
      fld_contact_phone: "5551234007",
      fld_contact_company: "ShopFlow",
      fld_contact_role: "COO",
      fld_contact_linkedin: "https://linkedin.com/in/rachelkim",
      fld_contact_tags: ["Decision Maker"],
      fld_contact_last_contacted: "2026-02-28",
    },
    {
      fld_contact_name: "David Brown",
      fld_contact_email: "david.brown@payguard.com",
      fld_contact_phone: "5551234008",
      fld_contact_company: "PayGuard",
      fld_contact_role: "CFO",
      fld_contact_linkedin: "https://linkedin.com/in/davidbrown",
      fld_contact_tags: ["Decision Maker"],
      fld_contact_last_contacted: "2026-03-12",
    },
    {
      fld_contact_name: "Anna Martinez",
      fld_contact_email: "anna@datapulse.ai",
      fld_contact_phone: "5551234009",
      fld_contact_company: "DataPulse Analytics",
      fld_contact_role: "Product Manager",
      fld_contact_linkedin: "https://linkedin.com/in/annamartinez",
      fld_contact_tags: ["Champion", "End User"],
      fld_contact_last_contacted: "2026-03-08",
    },
    {
      fld_contact_name: "Tom Harris",
      fld_contact_email: "tom@greenleaf.energy",
      fld_contact_phone: "5551234010",
      fld_contact_company: "GreenLeaf Energy",
      fld_contact_role: "Managing Director",
      fld_contact_linkedin: "https://linkedin.com/in/tomharris",
      fld_contact_tags: ["Decision Maker"],
      fld_contact_last_contacted: "2026-03-01",
    },
    {
      fld_contact_name: "Sophia Lee",
      fld_contact_email: "sophia.lee@securevault.com",
      fld_contact_phone: "5551234011",
      fld_contact_company: "SecureVault",
      fld_contact_role: "Head of Partnerships",
      fld_contact_linkedin: "https://linkedin.com/in/sophialee",
      fld_contact_tags: ["Champion", "Influencer"],
      fld_contact_last_contacted: "2026-03-19",
    },
    {
      fld_contact_name: "Ryan Taylor",
      fld_contact_email: "ryan.t@brightminds.edu",
      fld_contact_phone: "5551234012",
      fld_contact_company: "BrightMinds Academy",
      fld_contact_role: "Principal",
      fld_contact_linkedin: "https://linkedin.com/in/ryantaylor",
      fld_contact_tags: ["Decision Maker", "End User"],
      fld_contact_last_contacted: "2026-02-20",
    },
    {
      fld_contact_name: "Jessica Nguyen",
      fld_contact_email: "jessica@pixelforge.design",
      fld_contact_phone: "5551234013",
      fld_contact_company: "PixelForge",
      fld_contact_role: "Creative Director",
      fld_contact_linkedin: "https://linkedin.com/in/jessicanguyen",
      fld_contact_tags: ["Influencer"],
      fld_contact_last_contacted: "2026-03-05",
    },
    {
      fld_contact_name: "Kevin O'Brien",
      fld_contact_email: "kevin@healthsync.io",
      fld_contact_phone: "5551234014",
      fld_contact_company: "HealthSync",
      fld_contact_role: "VP of Operations",
      fld_contact_linkedin: "https://linkedin.com/in/kevinobrien",
      fld_contact_tags: ["Champion"],
      fld_contact_last_contacted: "2026-03-16",
    },
    {
      fld_contact_name: "Maria Garcia",
      fld_contact_email: "maria.garcia@swiftpay.co",
      fld_contact_phone: "5551234015",
      fld_contact_company: "SwiftPay",
      fld_contact_role: "Founder",
      fld_contact_linkedin: "https://linkedin.com/in/mariagarcia",
      fld_contact_tags: ["Decision Maker", "Champion"],
      fld_contact_last_contacted: "2026-03-24",
    },
    {
      fld_contact_name: "Chris Wright",
      fld_contact_email: "chris@retailedge.com",
      fld_contact_phone: "5551234016",
      fld_contact_company: "RetailEdge",
      fld_contact_role: "Head of Procurement",
      fld_contact_linkedin: "https://linkedin.com/in/chriswright",
      fld_contact_tags: ["Influencer", "End User"],
      fld_contact_last_contacted: "2026-02-15",
    },
    {
      fld_contact_name: "Natalie Scott",
      fld_contact_email: "natalie@novabyte.io",
      fld_contact_phone: "5551234017",
      fld_contact_company: "NovaByte",
      fld_contact_role: "Co-Founder",
      fld_contact_linkedin: "https://linkedin.com/in/nataliescott",
      fld_contact_tags: ["Decision Maker"],
      fld_contact_last_contacted: "2026-03-27",
    },
    {
      fld_contact_name: "Marcus Thompson",
      fld_contact_email: "marcus@eduwave.com",
      fld_contact_phone: "5551234018",
      fld_contact_company: "EduWave",
      fld_contact_role: "CTO",
      fld_contact_linkedin: "https://linkedin.com/in/marcusthompson",
      fld_contact_tags: ["Decision Maker", "Champion"],
      fld_contact_last_contacted: "2026-03-14",
    },
    {
      fld_contact_name: "Olivia Adams",
      fld_contact_email: "olivia@aerovista.com",
      fld_contact_phone: "5551234019",
      fld_contact_company: "AeroVista",
      fld_contact_role: "SVP of Sales",
      fld_contact_linkedin: "https://linkedin.com/in/oliviaadams",
      fld_contact_tags: ["Decision Maker"],
      fld_contact_last_contacted: "2026-03-21",
    },
    {
      fld_contact_name: "Daniel Foster",
      fld_contact_email: "daniel@wellnesshub.org",
      fld_contact_phone: "5551234020",
      fld_contact_company: "WellnessHub",
      fld_contact_role: "Program Director",
      fld_contact_linkedin: "https://linkedin.com/in/danielfoster",
      fld_contact_tags: ["End User"],
      fld_contact_last_contacted: "2026-01-30",
    },
    {
      fld_contact_name: "Aisha Patel",
      fld_contact_email: "aisha@acme.com",
      fld_contact_phone: "5551234021",
      fld_contact_company: "Acme Inc",
      fld_contact_role: "Engineering Manager",
      fld_contact_linkedin: "https://linkedin.com/in/aishapatel",
      fld_contact_tags: ["Champion", "End User"],
      fld_contact_last_contacted: "2026-03-11",
    },
  ];

  return contacts.map((data, index) => ({
    id: `rec_contact_${index + 1}`,
    objectId: "obj_contacts",
    data,
    createdAt: new Date(2025, 1, index + 1).toISOString(),
    updatedAt: new Date(2026, 2, 10 + (index % 18)).toISOString(),
  }));
}

function generateDealRecords(): TableRecord[] {
  const deals: Array<Record<string, unknown>> = [
    {
      fld_deal_name: "Acme Enterprise License",
      fld_deal_value: 250000,
      fld_deal_stage: "Negotiation",
      fld_deal_company: "Acme Inc",
      fld_deal_close_date: "2026-04-15",
      fld_deal_probability: 75,
      fld_deal_owner: "John Doe",
    },
    {
      fld_deal_name: "TechCorp Pilot Program",
      fld_deal_value: 45000,
      fld_deal_stage: "Qualification",
      fld_deal_company: "TechCorp Solutions",
      fld_deal_close_date: "2026-05-01",
      fld_deal_probability: 40,
      fld_deal_owner: "Jane Smith",
    },
    {
      fld_deal_name: "StartupXYZ Annual",
      fld_deal_value: 120000,
      fld_deal_stage: "Proposal",
      fld_deal_company: "StartupXYZ",
      fld_deal_close_date: "2026-04-30",
      fld_deal_probability: 60,
      fld_deal_owner: "John Doe",
    },
    {
      fld_deal_name: "MedVita Platform Expansion",
      fld_deal_value: 380000,
      fld_deal_stage: "Closed Won",
      fld_deal_company: "MedVita Health",
      fld_deal_close_date: "2026-03-01",
      fld_deal_probability: 100,
      fld_deal_owner: "John Doe",
    },
    {
      fld_deal_name: "LearnPath Team License",
      fld_deal_value: 28000,
      fld_deal_stage: "Prospecting",
      fld_deal_company: "LearnPath",
      fld_deal_close_date: "2026-06-15",
      fld_deal_probability: 20,
      fld_deal_owner: "Jane Smith",
    },
    {
      fld_deal_name: "CloudNine Migration Deal",
      fld_deal_value: 175000,
      fld_deal_stage: "Negotiation",
      fld_deal_company: "CloudNine Systems",
      fld_deal_close_date: "2026-04-10",
      fld_deal_probability: 80,
      fld_deal_owner: "Alex Rodriguez",
    },
    {
      fld_deal_name: "ShopFlow Integration",
      fld_deal_value: 92000,
      fld_deal_stage: "Proposal",
      fld_deal_company: "ShopFlow",
      fld_deal_close_date: "2026-05-20",
      fld_deal_probability: 55,
      fld_deal_owner: "Jane Smith",
    },
    {
      fld_deal_name: "PayGuard Enterprise Suite",
      fld_deal_value: 520000,
      fld_deal_stage: "Closed Won",
      fld_deal_company: "PayGuard",
      fld_deal_close_date: "2026-02-15",
      fld_deal_probability: 100,
      fld_deal_owner: "John Doe",
    },
    {
      fld_deal_name: "DataPulse Starter",
      fld_deal_value: 35000,
      fld_deal_stage: "Qualification",
      fld_deal_company: "DataPulse Analytics",
      fld_deal_close_date: "2026-06-01",
      fld_deal_probability: 35,
      fld_deal_owner: "Alex Rodriguez",
    },
    {
      fld_deal_name: "GreenLeaf Custom Build",
      fld_deal_value: 680000,
      fld_deal_stage: "Negotiation",
      fld_deal_company: "GreenLeaf Energy",
      fld_deal_close_date: "2026-04-25",
      fld_deal_probability: 70,
      fld_deal_owner: "John Doe",
    },
    {
      fld_deal_name: "SecureVault Pro",
      fld_deal_value: 210000,
      fld_deal_stage: "Proposal",
      fld_deal_company: "SecureVault",
      fld_deal_close_date: "2026-05-10",
      fld_deal_probability: 50,
      fld_deal_owner: "Jane Smith",
    },
    {
      fld_deal_name: "BrightMinds Campus",
      fld_deal_value: 65000,
      fld_deal_stage: "Closed Lost",
      fld_deal_company: "BrightMinds Academy",
      fld_deal_close_date: "2026-02-28",
      fld_deal_probability: 0,
      fld_deal_owner: "Alex Rodriguez",
    },
    {
      fld_deal_name: "PixelForge Studio License",
      fld_deal_value: 55000,
      fld_deal_stage: "Prospecting",
      fld_deal_company: "PixelForge",
      fld_deal_close_date: "2026-07-01",
      fld_deal_probability: 15,
      fld_deal_owner: "Jane Smith",
    },
    {
      fld_deal_name: "RetailEdge Full Platform",
      fld_deal_value: 340000,
      fld_deal_stage: "Closed Won",
      fld_deal_company: "RetailEdge",
      fld_deal_close_date: "2026-01-20",
      fld_deal_probability: 100,
      fld_deal_owner: "John Doe",
    },
    {
      fld_deal_name: "AeroVista Premium",
      fld_deal_value: 890000,
      fld_deal_stage: "Qualification",
      fld_deal_company: "AeroVista",
      fld_deal_close_date: "2026-08-01",
      fld_deal_probability: 30,
      fld_deal_owner: "Alex Rodriguez",
    },
    {
      fld_deal_name: "SwiftPay Starter Pack",
      fld_deal_value: 18000,
      fld_deal_stage: "Prospecting",
      fld_deal_company: "SwiftPay",
      fld_deal_close_date: "2026-07-15",
      fld_deal_probability: 10,
      fld_deal_owner: "Jane Smith",
    },
  ];

  return deals.map((data, index) => ({
    id: `rec_deal_${index + 1}`,
    objectId: "obj_deals",
    data,
    createdAt: new Date(2025, 3, index + 1).toISOString(),
    updatedAt: new Date(2026, 2, 5 + (index % 24)).toISOString(),
  }));
}

export function getMockRecords(objectId: string): TableRecord[] {
  switch (objectId) {
    case "obj_companies":
      return generateCompanyRecords();
    case "obj_contacts":
      return generateContactRecords();
    case "obj_deals":
      return generateDealRecords();
    default:
      return [];
  }
}
