import type { StoreInfo } from "../types";

export const mockDelistArticles = [
  {
    articleCode: "310080351",
    articleName: 'CORNSTARCH BIODEGRADABLE BAGN ROLL10X14"',
    subCategory: "OTHERS",
    affectedCount: 5,
    rangedCount: 5,
  },
  {
    articleCode: "310087574",
    articleName: 'MINI SEL ,PLAIN, 3" CORE',
    subCategory: "DISPLAY MATERIAL",
    affectedCount: 6,
    rangedCount: 6,
  },
];

export const mockStoresByArticle: Record<string, StoreInfo[]> = {
  "310080351": [
    {
      name: "RCP",
      code: "5518",
      state: "MAH",
      city: "NAVI MUMBAI",
      classificationMatrix: 14,
      salesVelocity: 0.0,
      revenueContribution: 0,
    },
    {
      name: "Acme Mall",
      code: "6217",
      state: "MAH",
      city: "MUMBAI",
      classificationMatrix: 14,
      salesVelocity: 0.0,
      revenueContribution: 0,
    },
    {
      name: "Phoenix Market City",
      code: "6220",
      state: "MAH",
      city: "MUMBAI",
      classificationMatrix: 14,
      salesVelocity: 0.0,
      revenueContribution: 0,
    },
    {
      name: "D Victoria Mall",
      code: "6221",
      state: "MAH",
      city: "MUMBAI",
      classificationMatrix: 14,
      salesVelocity: 0.0,
      revenueContribution: 0,
    },
    {
      name: "Centre Point",
      code: "CP01",
      state: "MAH",
      city: "NAVI MUMBAI",
      classificationMatrix: 14,
      salesVelocity: 0.0,
      revenueContribution: 0,
    },
  ],
  "310087574": [
    {
      name: "RCP",
      code: "5518",
      state: "MAH",
      city: "NAVI MUMBAI",
      classificationMatrix: 14,
      salesVelocity: 0.0,
      revenueContribution: 0,
    },
    {
      name: "Acme Mall",
      code: "6217",
      state: "MAH",
      city: "MUMBAI",
      classificationMatrix: 14,
      salesVelocity: 0.0,
      revenueContribution: 0,
    },
    {
      name: "Phoenix Market City",
      code: "6220",
      state: "MAH",
      city: "MUMBAI",
      classificationMatrix: 14,
      salesVelocity: 0.0,
      revenueContribution: 0,
    },
    {
      name: "D Victoria Mall",
      code: "6221",
      state: "MAH",
      city: "MUMBAI",
      classificationMatrix: 14,
      salesVelocity: 0.0,
      revenueContribution: 0,
    },
    {
      name: "Centre Point",
      code: "CP01",
      state: "MAH",
      city: "NAVI MUMBAI",
      classificationMatrix: 14,
      salesVelocity: 0.0,
      revenueContribution: 0,
    },
    {
      name: "Smart Badlapur West",
      code: "TAJF",
      state: "MAH",
      city: "BADLAPUR",
      classificationMatrix: 14,
      salesVelocity: 0.0,
      revenueContribution: 0,
    },
  ],
};

export const mockDelistReasons = [
  "Low sales performance",
  "Product discontinued by manufacturer",
  "Supplier reliability or delivery issues",
  "Quality or defect issues",
  "Seasonal/temporary product",
  "Customer complaints",
  "Regulatory/compliance issues",
];
