import type { ClassificationCell, NOBCategory, RangedArticle } from "../types";

export const mockClassificationMatrix: ClassificationCell[] = [
  {
    code: "AX",
    revenue: "A",
    demandStability: "X",
    percentage: 2.72,
    skuType: "strategic",
  },
  {
    code: "AY",
    revenue: "A",
    demandStability: "Y",
    percentage: 2.41,
    skuType: "strategic",
  },
  {
    code: "AZ",
    revenue: "A",
    demandStability: "Z",
    percentage: 0.95,
    skuType: "regular",
  },
  {
    code: "BX",
    revenue: "B",
    demandStability: "X",
    percentage: 8.59,
    skuType: "regular",
  },
  {
    code: "BY",
    revenue: "B",
    demandStability: "Y",
    percentage: 4.8,
    skuType: "regular",
  },
  {
    code: "BZ",
    revenue: "B",
    demandStability: "Z",
    percentage: 1.59,
    skuType: "review",
  },
  {
    code: "CX",
    revenue: "C",
    demandStability: "X",
    percentage: 53.84,
    skuType: "review",
  },
  {
    code: "CY",
    revenue: "C",
    demandStability: "Y",
    percentage: 15.62,
    skuType: "review",
  },
  {
    code: "CZ",
    revenue: "C",
    demandStability: "Z",
    percentage: 9.49,
    skuType: "review",
  },
];

export const mockNOBCategories: NOBCategory[] = [
  {
    name: "Bulk Items",
    description: "Low Bills & High Volume",
    skuCount: 1102,
    billsPct: 0.02,
    volumePct: 0.04,
    avgUPB: 2.96,
    color: "var(--primary-50)",
  },
  {
    name: "Core SKU",
    description: "High Bills & High Volume",
    skuCount: 47334,
    billsPct: 99.45,
    volumePct: 99.65,
    avgUPB: 1.61,
    color: "var(--success-50)",
  },
  {
    name: "Habitual Picks",
    description: "High Bills & Low Volume",
    skuCount: 697,
    billsPct: 0.03,
    volumePct: 0.01,
    avgUPB: 0.38,
    color: "var(--secondary-50)",
  },
  {
    name: "Rationalize",
    description: "Low Bills & Low Volume",
    skuCount: 36716,
    billsPct: 0.5,
    volumePct: 0.31,
    avgUPB: 1.01,
    color: "var(--error-50)",
  },
];

export const mockRangedArticles: RangedArticle[] = [
  {
    articleCode: "1590001701",
    articleName: "APPLE JAMMU KASHMIR MEDIUM NON RR",
    storeCount: 9,
    subCategory: "APPLE (INDIAN)",
    brick: "APPLE KASHMIR",
    classification: "-",
  },
  {
    articleCode: "310080351",
    articleName: 'CORNSTARCH BIODEGRADABLE BAGN ROLL10X14"',
    storeCount: 5,
    subCategory: "OTHERS",
    brick: "OTHERS",
    classification: "-",
  },
  {
    articleCode: "310087574",
    articleName: 'MINI SEL ,PLAIN, 3" CORE',
    storeCount: 6,
    subCategory: "DISPLAY MATERIAL",
    brick: "TAG SEL",
    classification: "-",
  },
  {
    articleCode: "310087656",
    articleName: "IMPORTED VHB ADHESIVE TAPE 12MMX50 MTR",
    storeCount: 6,
    subCategory: "BROWN TAPE",
    brick: "BROWN TAPE",
    classification: "-",
  },
  {
    articleCode: "310089510",
    articleName: '100% COTTON BAG SIZE-19" X 20",2 COL_VF',
    storeCount: 2,
    subCategory: "BAGS",
    brick: "CARRY BAGS",
    classification: "BY",
  },
  {
    articleCode: "310092446",
    articleName: "COMPOSTABLE KIRANA BAG 1KG-7X12.5 -20MIC",
    storeCount: 5,
    subCategory: "PACKAGING",
    brick: "PACKAGING",
    classification: "-",
  },
  {
    articleCode: "310092447",
    articleName: "COMPOSTABLE KIRANA BAG 3 KG-11X15 -25MIC",
    storeCount: 2,
    subCategory: "PACKAGING",
    brick: "PACKAGING",
    classification: "-",
  },
  {
    articleCode: "310092448",
    articleName: "COMPOSTABLE KIRANA BAG 5 KG-13X18 - 3MIC",
    storeCount: 6,
    subCategory: "PACKAGING",
    brick: "PACKAGING",
    classification: "-",
  },
  {
    articleCode: "310097791",
    articleName: 'PEG HOOK WHITE SEL 40X75MM- 3" CORE',
    storeCount: 10,
    subCategory: "DISPLAY MATERIAL",
    brick: "TAG SEL",
    classification: "-",
  },
];
