import type { DelistRequest, RequestDetail } from "../types";

export const mockRequests: DelistRequest[] = [
  {
    requestId: "RQ20260402142441",
    requestTime: "2026-04-02T14:24:00",
    requestedBy: "ayushtiwari@gofynd.com",
    requestType: "Delist",
    category: "CONSUMABLES",
    storeCount: 13,
    productCount: 2,
    reason: "Product discontinued by manufacturer",
    status: "Pending",
  },
  {
    requestId: "RQ20260402140330",
    requestTime: "2026-04-02T14:03:00",
    requestedBy: "ayushtiwari@gofynd.com",
    requestType: "Delist",
    category: "PACKAGING",
    storeCount: 10,
    productCount: 2,
    reason: "Supplier reliability or delivery issues",
    status: "Pending",
  },
  {
    requestId: "RQ20260402070448",
    requestTime: "2026-04-02T07:04:00",
    requestedBy: "ayushtiwari@gofynd.com",
    requestType: "Delist",
    category: "PACKAGING",
    storeCount: 4,
    productCount: 1,
    reason: "Low sales performance",
    status: "Pending",
  },
  {
    requestId: "RQ20260402070347",
    requestTime: "2026-04-02T07:03:00",
    requestedBy: "ayushtiwari@gofynd.com",
    requestType: "Delist",
    category: "PACKAGING",
    storeCount: 9,
    productCount: 2,
    reason: "Low sales performance",
    status: "Pending",
  },
  {
    requestId: "RQ20260402070111",
    requestTime: "2026-04-02T07:01:00",
    requestedBy: "ayushtiwari@gofynd.com",
    requestType: "Delist",
    category: "PACKAGING",
    storeCount: 7,
    productCount: 2,
    reason: "Low sales performance",
    status: "Pending",
  },
  {
    requestId: "RQ20260402070035",
    requestTime: "2026-04-02T07:00:00",
    requestedBy: "ayushtiwari@gofynd.com",
    requestType: "Delist",
    category: "PACKAGING",
    storeCount: 6,
    productCount: 1,
    reason: "Low sales performance",
    status: "Pending",
  },
  {
    requestId: "RQ20260402065555",
    requestTime: "2026-04-02T06:55:00",
    requestedBy: "ayushtiwari@gofynd.com",
    requestType: "Delist",
    category: "PREMIUM FRUITS",
    storeCount: 222,
    productCount: 50,
    reason: "Low sales performance",
    status: "Pending",
  },
  {
    requestId: "RQ20260325072125",
    requestTime: "2026-03-25T07:21:00",
    requestedBy: "ayushtiwari@gofynd.com",
    requestType: "Delist",
    category: "PALM OIL",
    storeCount: 27,
    productCount: 4,
    reason: "Quality or defect issues",
    status: "Pending",
  },
  {
    requestId: "RQ20260324103915",
    requestTime: "2026-03-24T10:39:00",
    requestedBy: "ayushtiwari@gofynd.com",
    requestType: "Delist",
    category: "MAJOR CERELAS",
    storeCount: 32,
    productCount: 3,
    reason: "Low sales performance",
    status: "Pending",
  },
];

export const mockRequestDetail: RequestDetail = {
  requestId: "RQ20260402142441",
  status: "Pending",
  category: "CONSUMABLES",
  subCategory: "BAGS",
  format: "All",
  zone: "All",
  state: "All",
  requestType: "Delist",
  requestTime: "2026-04-02T14:24:00",
  requestedBy: "ayushtiwari@gofynd.com",
  raisedOn: "2026-04-02T14:24:00",
  raisedBy: "ayushtiwari@gofynd.com",
  storeCount: 13,
  productCount: 2,
  reason: "Product discontinued by manufacturer",
  articles: [
    {
      articleCode: "310087573",
      articleName: 'MINI SEL ,PLAIN, 1" CORE',
      subCategory: "OTHERS",
      affectedStores: 0,
      totalStores: 11,
      reason: "Product discontinued by manufacturer",
      stores: [
        { name: "RCP", code: "5518", state: "MAH", city: "NAVI MUMBAI" },
        { name: "Acme Mall", code: "6217", state: "MAH", city: "MUMBAI" },
        {
          name: "Phoenix Market City",
          code: "6220",
          state: "MAH",
          city: "MUMBAI",
        },
        {
          name: "D Victoria Mall",
          code: "6221",
          state: "MAH",
          city: "MUMBAI",
        },
        {
          name: "SBZ-DOMBIVILI-LODHA",
          code: "FR00",
          state: "MAH",
          city: "MUMBAI",
        },
      ],
    },
    {
      articleCode: "310081660",
      articleName: "PLAIN WHITE COTTON BAG SIZE18...",
      subCategory: "BAGS",
      affectedStores: 0,
      totalStores: 2,
      reason: "Product discontinued by manufacturer",
      stores: [
        { name: "RCP", code: "5518", state: "MAH", city: "NAVI MUMBAI" },
        { name: "Acme Mall", code: "6217", state: "MAH", city: "MUMBAI" },
      ],
    },
  ],
};
